### ISSUE TITLE
Add copy/cut/paste buttons to code and sprite editor

### ISSUE THREAD

**Issue by trelemar** [nesbox/tic.computer#49] opened 2017-02-14 12:02 UTC
Being able to use TIC on Android is great, however CTRL+C, CTRL+V do not work making it difficult to create animations, or fixing some code issues without redrawing and retyping.
Maybe we can have cut, copy and paste buttons along the top right of the header bar? Or with the other tools in the sprite editor?

Undo and redo would be a nice touch as well.

**Comment by nesbox** [comment] 2017-02-14 12:04
Do you use TIC on Android with external keyboard?

**Comment by trelemar** [comment] 2017-02-14 12:11
I have one that I use sometimes but it can be clunky when working from the couch,  I've never tried the hotkeys on Android with the external keyboard however. I do know that using hacker's keyboard and pressing ctrl+c, ctrl+v does nothing. When using other apps these hotkeys work fine with the soft-keyboard.

**Comment by nesbox** [comment] 2017-02-14 12:14
ok, will try to fix `ctrl+c` `ctrl+v` on hacker's keyboard at first

**Comment by trelemar** [comment] 2017-02-14 12:46
Cool thanks! Also, if we have a few feature request, should we open issues for each of them? Or is there a better place for feature requests?

**Comment by nesbox** [comment] 2017-02-14 12:52
I think Github is a good place for feature requests.

**Comment by nesbox** [comment] 2017-02-23 19:07
I installed _hacker's keyboard_ and noticed that `ctrl+c` works on my device, cannot reproduce :(
As variant I added other shortcuts `shift+del` `ctrl+insert` `shift+insert` to cut/copy/paste.

Also I added small toolbar with `cut` `copy` `paste` `undo` `redo` buttons to all the editors.
Here is an example it looks in .19

![bar](https://cloud.githubusercontent.com/assets/1101448/23274277/2a30b3ec-fa13-11e6-9637-eabbeb88c5f7.gif)

closing on .19

**Closed by nesbox** 2017-02-23 19:07 UTC
Labels: android, bug

**Comment by trelemar** [comment] 2017-02-23 19:17
Thank you for the toolbar! And ctrl+c, ctrl+v does not work on both of my devices, a Moto G4 and a Galaxy Tab 4. Here's a short video of it not working. Results are the same on both devices: https://youtu.be/Ld-3TXwWCbA

**Comment by nesbox** [comment] 2017-02-23 19:45
hmm, try to go to 
`settings > language and input > hacker's keyboard settings > ctrl key code > select 'left ctrl'`
and try to reproduce

**Comment by trelemar** [comment] 2017-02-23 19:53
That was it. Working now. Sorry!

**Comment by nesbox** [comment] 2017-02-23 19:55
no problem 😃
