### ISSUE TITLE
Alt-1 adds "1" to the editor

### ISSUE THREAD

**Issue by benob** [nesbox/tic.computer#277] opened 2017-08-28 13:09 UTC
When pressing Alt-1 to switch to the editor, it adds the character "1" to where the cursor is, modifying the code.

**Comment by nesbox** [comment] 2017-08-28 13:15
Can't reproduce on Win and Html version.
What system do you use?

**Comment by benob** [comment] 2017-08-28 20:30
Linux x64 (tried v0.30 and v0.40). Elementary OS (Ubuntu 16.04 based).

**Comment by nesbox** [comment] 2017-08-29 13:11
fixed in .40

**Closed by nesbox** 2017-08-29 13:11 UTC
Labels: bug
