### ISSUE TITLE
bug/feature? add trace() output to console

### ISSUE THREAD

**Issue by to90zeroblue** [nesbox/tic.computer#188] opened 2017-06-15 23:47 UTC
When running TIC80 through command line, I would like to have outputs from trace() in the terminal window. Maybe a command line argument -t ?

**Comment by nesbox** [comment] 2017-06-16 04:55
info for me
https://stackoverflow.com/questions/3009042/how-to-view-printf-output-in-a-win32-application-on-visual-studio-2010

**Comment by nesbox** [comment] 2017-07-05 19:28
close duplicate of #173

**Closed by nesbox** 2017-07-05 19:28 UTC
Labels: enhancement
