### ISSUE TITLE
btn(x) not working correctly under Linux

### ISSUE THREAD

**Issue by flautines** [nesbox/tic.computer#205] opened 2017-06-22 06:54 UTC
Steps to reproduce the issue
- Under linux execute the tic executable (chmod +x first)
- At the ">" prompt type 'run' to execute the default example
- The sprite goes away diagonally. 

I tested it and it seems that btn(0) and btn(2) returns true even if no keys are pressed.

Tested with tic 0.28.1 dev (downloaded from the tic-80 tiny computer page) under Linux manjaro-openrc 4.9.27-1

**Comment by RafaelOliveira** [comment] 2017-06-27 18:29
I'm also seeing this in 0.28.1 dev. I thought it was my keyboard, but now I'm seeing it here.

**Comment by nesbox** [comment] 2017-06-27 19:13
@RafaelOliveira also Linux?

**Comment by RafaelOliveira** [comment] 2017-06-27 19:56
Yes, Linux Mint.

**Comment by nesbox** [comment] 2017-06-27 20:30
could someone test this version?
[tic_btn_test.tar.gz](https://github.com/nesbox/tic.computer/files/1106664/tic_btn_test.tar.gz)
thanks

**Comment by trelemar** [comment] 2017-06-27 20:33
This is odd. I use Ubuntu Mate 64 bit with TIC with no button issues at all.

**Comment by RafaelOliveira** [comment] 2017-06-27 21:30
@nesbox this version fix the problem (for me), thanks!

**Comment by nesbox** [comment] 2017-06-27 21:41
@RafaelOliveira hmm, I disabled joysticks and touch input in this build
Do you have connected gamepad or joystick while you run TIC?

**Comment by RafaelOliveira** [comment] 2017-06-27 21:44
The only things connected here are a wireless mouse and a bluetooth speaker.

**Comment by RafaelOliveira** [comment] 2017-06-27 21:53
I found the problem. It's my mouse, a microsoft wireless mouse. I startet TIC with the mouse unpluged, and everything was ok. With the example running, when I plug the mouse, the sprite start to move alone (turning on the key automatically).

**Comment by nesbox** [comment] 2017-06-27 21:56
@RafaelOliveira ok, pls test this one with disabled touch input [tic_touch_input_disabled.tar.gz](https://github.com/nesbox/tic.computer/files/1106923/tic_touch_input_disabled.tar.gz)
seems TIC recognizes your mouse as touch device

**Comment by RafaelOliveira** [comment] 2017-06-27 22:00
This version is still happening the problem.

**Comment by RafaelOliveira** [comment] 2017-06-27 22:11
I'm seeing something here about microsoft devices being detected like joysticks, so I will test this.
https://github.com/denilsonsa/udev-joystick-blacklist

**Comment by nesbox** [comment] 2017-06-27 22:19
😲 OMG
pls let us know if you find something
TIC is built with SDL, so you can try to test connected joysticks with https://github.com/Grumbel/sdl-jstest

**Comment by RafaelOliveira** [comment] 2017-06-27 22:34
yeah, the tool detected one joystick:
"Microsoft Microsoft® 2.4GHz Transceiver v8.0" (the mouse)
The problem is not in TIC, I will test the other link.

**Comment by RafaelOliveira** [comment] 2017-06-27 22:53
The first command worked for me. Here:
https://github.com/denilsonsa/udev-joystick-blacklist
I need to unplug the mouse receiver for the patch to work.
@flautines check if this is you problem too. I tested first with https://github.com/Grumbel/sdl-jstest

**Comment by nesbox** [comment] 2017-07-04 14:14
so, it's not TIC issue
closing

**Closed by nesbox** 2017-07-04 14:14 UTC
