### ISSUE TITLE
Сopy and paste blocks of sprites in the Map Editor

### ISSUE THREAD

**Issue by KochkinBochkin** [nesbox/tic.computer#19] opened 2017-01-28 16:10 UTC
It would be nice to be able to copy and paste blocks of sprites in the Map Editor

**Comment by nesbox** [comment] 2017-01-28 16:32
will do, thanks

**Comment by nesbox** [comment] 2017-06-06 17:20
duplicate of #132 closing

**Closed by nesbox** 2017-06-06 17:20 UTC
Labels: enhancement
