### ISSUE TITLE
A bug in Android version

### ISSUE THREAD

**Issue by RainEffect** [nesbox/tic.computer#4] opened 2017-01-16 12:43 UTC
My Android phone is connected to the keyboard.
I can't use other than the arrow keys to control when I running my code.
And if I switch the apps, when I open the TIC again, it will not be able to input, only can restart.

**Comment by hseiken** [comment] 2017-01-18 14:14
Using galaxy tab 4 with BT keyboard and mouse creates issue where pushing 'z' locks button 1.  It's indicated on screen as always triggered.  As well, the onscreen keyboard doesn't respond well, requiring super fast double tap 'back' to trick the keyboard to say off screen, which then allows user to push the 'back' button mapped to ESC to switch between code and shell.  

Everything else works, though.  However, with the buttons stuck using keyboard and mouse when testing games, it's not usable since every test play requires restarting the entire software to fix the stuck button.

**Comment by hseiken** [comment] 2017-02-22 02:51
New bug (with workaround).  On android, using virtual keys (gboard or in my case "HackerKeys" app), when the app goes to sleep and is brought back into focus, the keyboard doesn't work.  To get around this, if you're on the code view, switching to other menus (i.e. sprite or map editors) then back to the code will reset the keyboard  to work again.  Likewise, if you are in the console, mashing BACK button on your device a couple of times to get to the code section to do the menu change will allow the keyboard app to connect back into TiC.

Currently, bluetooth state changes still crash TiC, so it's still not quite useable with real keyboard yet.

**Comment by nesbox** [comment] 2017-02-23 20:30
@hseiken I found a solution for BT keyboard https://forums.libsdl.org/viewtopic.php?t=12292&sid=8174f986c4bd1d2cb9ac5b5293221ba4 and made fix
could you pls test it, because unfortunately I don't have BT keyboard to check

[tic.zip](https://github.com/nesbox/tic.computer/files/797660/tic.zip)

**Comment by trelemar** [comment] 2017-02-23 20:37
I can test this when I get home. I have a similar setup to @hseiken, Galaxy tab 4 and Bluetooth keyboard.

**Comment by nesbox** [comment] 2017-02-23 20:40
Great, waiting for results :) ...

**Comment by hseiken** [comment] 2017-02-23 20:45
It works, no crashing from BT connect/disconnect.  Nice one.  :)

**Comment by nesbox** [comment] 2017-02-23 20:48
Does text input work from your BT keyboard?

**Comment by hseiken** [comment] 2017-02-23 20:51
Yes, input successfully switches between the two, arrow keys work, shift+arrow to select multiple lines works.  The previous problem of the software keyboard still persists, but BT keyboard does connect and disconnect and enter text, even after sleep/app switching.  FKeys work, etc.  American keyboard layout and android system.

**Comment by nesbox** [comment] 2017-02-23 21:06
Well, I'm going to add touch button to show/hide software keyboard or smth else...

**Comment by nesbox** [comment] 2017-02-24 11:10
I made a fix for software keyboard on Android version, keyboard shows on startup and when you touch screen in portrait mode, landscape mode works without screen keyboard

you can check
[tic_soft_keyboard_fix.zip](https://github.com/nesbox/tic.computer/files/799085/tic_soft_keyboard_fix.zip)

closing on .19

**Comment by nesbox** [comment] 2017-02-24 11:50
I forgot to check BT keyboard support, reopen...

**Comment by trelemar** [comment] 2017-02-24 16:56
This method works great before you switch apps, after that I cannot get the keyboard to come up at all.

**Comment by trelemar** [comment] 2017-02-24 17:35
Here's a video showing exactly what I'm experiencing: https://youtu.be/WTj2O6Rago4 hope that helps.

**Comment by nesbox** [comment] 2017-02-24 19:51
@trelemar thanks for intelligible explanation, I think the problem is inside SDL lib I used in the TIC project
so, I made another one fix, pls test
[tic_android_kb_fix.zip](https://github.com/nesbox/tic.computer/files/800316/tic_android_kb_fix.zip)

**Comment by trelemar** [comment] 2017-02-24 20:13
Played with it for 5 minutes after installing that version and could not reproduce the issue. Awesome work :) Almost time for a 0.19.0 release eh? :D

**Comment by hseiken** [comment] 2017-02-24 20:19
I can say it's working 95% as expected.  It's not 'fast' to detect changes in keyboard types, but I haven't had to restart/restore or anything like that to switch between BT and soft keys.  Works well!  I tested by typing with soft keys, turning on bt, typing with it, going into running cart, then to edit, take off bt keyboard then bring up soft keys then bt again.   Everything works.

**Comment by nesbox** [comment] 2017-02-24 20:22
perfect!
thanks to all
closing on .19

**Closed by nesbox** 2017-02-24 20:22 UTC
Labels: android, bug
