### ISSUE TITLE
Code Editor Background Color Glitch

### ISSUE THREAD

**Issue by gusg21** [nesbox/tic.computer#265] opened 2017-08-14 15:30 UTC
I was editing a sprite in my game, and when I finished and returned to the code editor, it looked like this:

![image](https://user-images.githubusercontent.com/14032977/29278831-dbbf5f58-80e3-11e7-980e-3076339c6613.png)

I'm running Windows 10 x64.

**Comment by Jusstas** [comment] 2017-08-14 22:11
You changed that color in palette

**Comment by ChildishGiant** [comment] 2017-08-15 07:05
All the colors in the editor are based off the color palette. This is one of the reasons why I use an external code editor.

**Comment by gusg21** [comment] 2017-08-15 12:30
Oh. Why is that a feature(/bug)? That doesn't seem helpful.

**Comment by ChildishGiant** [comment] 2017-08-15 12:47
Pretty sure it's trying to stick to the whole concept of palette limitations but I also think it's a bad idea, yet don't know how to get around it while keeping the palette.

**Comment by gusg21** [comment] 2017-08-15 12:55
I just swapped around the colors on my palette to make it a little (little) bit better.

**Comment by trelemar** [comment] 2017-08-15 13:03
Instead of rearranging the color palette, you can modify the PALMAP in `config`. The palmap will effect what color indicies TIC-80's editors use, and doesn't effect your game's colors.

```
PALMAP="0123456789abcdef"
```
Where `abcdef` are colors 10-15. Just switch the order of your string to change the map around. Hope this helps.

_Sent from my HONOR FRD-L04 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nesbox** [comment] 2017-08-21 15:35
it's by design, the editors and your game have the same Video RAM and palette as a result
closing...

**Closed by nesbox** 2017-08-21 15:35 UTC
