### ISSUE TITLE
Trace output redirecting to file is not working while using more arguments.

### ISSUE THREAD

**Issue by Crutiatix** [nesbox/tic.computer#125] opened 2017-05-10 12:42 UTC
- `tic > out.txt` - working
- `tic > out.txt -code source.lua` - **not working**
- `tic > out.txt source.tic` - **not working**
- `tic source.tic -code source.lua > out.txt` - **not working**

When using more arguments the output file is created, but is empty.

**Comment by nesbox** [comment] 2017-05-24 19:55
I can't reproduce it, I tested all your cases and all is working fine (I used Windows and CMD console)
any additional info, OS and etc?

**Comment by Effer** [comment] 2017-05-24 20:01
Also for me worked in console, but I'm having some problem to make it work with notepad++ and maybe it's related.

`<Command name="TIC_Log" Ctrl="no" Alt="yes" Shift="no" Key="82">C:\Users\Filippo\Dropbox\PC-Programmi\TIC\tic.exe -code &quot;$(FULL_CURRENT_PATH)&quot; &gt; &quot;$(CURRENT_DIRECTORY)\log.txt&quot;</Command>`

**Comment by nesbox** [comment] 2017-06-07 06:49
can't reproduce :/
closing...

**Comment by Crutiatix** [comment] 2017-06-07 17:47
Sooooorry, I have no idea why I didn't notice new posts in this thread. I check news at github every day, however I noticed it just now 😞 
Anyway I reproduced the problem again. Maybe I am doing something wrong. I'm using Windows 10 (yes, shame me, just for sure.) 
Created a file named test.lua with the content:
`trace("Lorem ipsum dolor sit amet",5)`
Ran command:
`tic.exe > out.txt -code test.lua` (test.lua is in the actual dir)
The result is the **blank** new file out.txt.
Also tried to create the blank test.tic file and ran command:
'tic.exe test.tic > out.txt -code test.lua
The result is same. Also tried the redirect and code in reversed order.

**Comment by nesbox** [comment] 2017-06-07 17:49
do you use _cmd_ or maybe _powershell_?

**Comment by Crutiatix** [comment] 2017-06-07 17:54
You got it! 😄 
The problem is only when using powershell. Everyting works in cmd. Microsoft made PS as default so it affects the notepad++ when running commands too 😠

**Comment by nesbox** [comment] 2017-06-07 17:56
great, so, closing then :)
thanks

**Closed by nesbox** 2017-06-07 17:56 UTC
Labels: bug

**Comment by Crutiatix** [comment] 2017-06-07 18:18
Sorry for reopen the issue. Just want to share the solution for this problem. The powershell should support redirecting command ">" but it doesn't work with TIC. 
However I found this command working for TIC in powershell:  
`tic.exe -code test.lua | Out-File out.txt`

**Comment by nesbox** [comment] 2017-06-07 18:27
could you pls add the info you found on the Wiki?

**Comment by Effer** [comment] 2017-06-07 18:28
@Crutiatix  are you using notepad++ ?
I'm still facing problem to output trace to a file in notepad++ with a macro.

**Comment by Crutiatix** [comment] 2017-06-07 18:50
@nesbox sure :)

@Effer Yes, me too. 😕  I try to figure out someting.

**Comment by Crutiatix** [comment] 2017-06-07 19:21
@Effer This works for me:
Run.. (F5)
`powershell -Command tic.exe -cart C:\Users\Username\AppData\Roaming\TIC-80\0.26.0 dev\$(NAME_PART).tic -code $(FILE_NAME) | Out-File log.txt`
Need to write full path to the TIC dir. %APPDATA% doesn't work.

**Comment by Effer** [comment] 2017-06-07 19:56
@Crutiatix , thanks for sharing!
Starting from your input I menage to run it using command prompt t instead of powershell:

`cmd /c C:\Users\Filippo\Dropbox\PC-Programmi\TIC\tic.exe -code $(FULL_CURRENT_PATH) > $(CURRENT_DIRECTORY)\out.txt`

It take less time then powershell to start, still the prompt is visibile in background, but I can live with it. Here my tic is on a dropbox folder with the project I'm working to. So I have a portable fantasy console shared with my computers :)

**Comment by Crutiatix** [comment] 2017-06-07 20:32
@Effer thanks too!
I had been using a similar command before, but after `cmd /C` I had `start` command yet which was making problems. 

Same as you I use a cloud for this purpose but instead dropbox I'm using google drive 😄
