### ISSUE TITLE
add hotkey for comment/uncomment

### ISSUE THREAD

**Issue by Gi972** [nesbox/tic.computer#95] opened 2017-04-08 09:19 UTC
Hello,

It's possible to add a hotkeys for comment / uncomment the code in the text editor when you highlight ?

**Comment by Crutiatix** [comment] 2017-04-08 11:24
A question is how complex code editor we want. I think, that one of the basic ideas of TIC-80 is a simplicity so adding shortcuts for any little gimmick goes against this idea. 

However, useful feature which is common in many code editors would by closing a selected text into a parenthesis `()[]{}""''` and in lua also `-` respectively `--`. This could partially solve @Gi972 's request.

**Comment by harraps** [comment] 2017-04-08 11:40
I think plugins for Atom, VSCode, SublimText, Brackets, Notepad++ would be a really good idea.

**Comment by Gi972** [comment] 2017-04-08 11:44
I'm alright with you,

In fact is more suggestions for improve experience when you write code and reflex pratices and increase productivity. Free of you to implement this or not :-)

@Harraps I prefer stay on the tic editor because I can run quickly when i debug :-)

**Comment by Gi972** [comment] 2017-04-08 11:49
by the way @nesbox it's possible open the file with a external editor?

**Comment by Crutiatix** [comment] 2017-04-08 12:12
@Gi972 It's not a problem to run fast a code from external editor in TIC. 
Just if you add to _PATH_ enviroment variable a path to tic.exe and then setup a build commands in editor:
SublimeText: Tools > Build System > New Build System... and then input into new created file:
```javascript
{
"shell_cmd": ["tic", "%APPDATA%Roaming/TIC-80/0.21.0 dev/$file_base_name.tic","-code","$file"]
}
``` 
Save and then CTRL+B for build.
It's just example. I'm not sure if it works. I'm using Atom :D

**Comment by Gi972** [comment] 2017-04-08 16:59
Ok @Crutiatix I code with visual studio code, I will try with it, thanks for the tips ;-)

**Comment by Gi972** [comment] 2017-04-08 22:51
@Crutiatix ,

Are you on mac or pc?

I try on sublime text 3 but when I save TIC build system it don't appear on the menu :-/
So I cant build.
And I cant open a file too...

@nesbox  if possible launch a file from terminal? with argument for launch directly a file?

**Comment by nesbox** [comment] 2017-04-09 06:32
@Gi972 
Using external editors in TIC-80 - https://github.com/nesbox/tic.computer/wiki#using-external-code-editors

Could you pls provide exact info how to reproduce:

> "tetris.tic", line 1, col 1: Illegal character (expected alphanumeric or @%&*!#) - '^A'

**Comment by Gi972** [comment] 2017-04-09 07:08
When I open terminal on the repertory of game folder I write I :

```
MacBook-Pro-de-Gi:0.21.0 dev j3di$ tic tetris.tic 

"tetris.tic", line 1, col 1: Illegal character (expected alphanumeric or @%&*!#) - '^A'
```
I try too

```
MacBook-Pro-de-Gi:Applications j3di$ open "tic.app tetris.tic"

The file /Applications/tic.app tetris.tic does not exist.
```
or 

```
MacBook-Pro-de-Gi:Applications j3di$ open "tic.app" --args tetris.tic
```
it's launch tic but don't load

maybe I don't use the good command, hum hum :-D

Could you give me steps to follow?...

**Comment by nesbox** [comment] 2017-04-09 07:50
@Gi972 I got the problem
* in the first case you are calling 'tic' from /usr/bin/tic and it's another's process, not TIC-80
* in the second, you are trying to pass args to app package `tic.app`, TIC loads but without cart, here you have to pass full path to the cart `$ open ./tic.app --args ~/Desktop/tic/tetris.tic` to open local .app package or `$ open -a tic --args ~/Desktop/tic/tetris.tic` to open installed package
* also you can call `tic` directly from inside .app package `$ tic.app/Contents/MacOS/tic tetris.tic`, in this case you can use relative paths to the cart

**Comment by Gi972** [comment] 2017-04-09 09:10
@nesbox 

Ok 

I copy the code of tetris. ti c in tetris.lua

I try

```
 MacBook-Pro-de-Gi:Tic j3di$ /Applications/tic.app/Contents/MacOS/tic tetris.tic -code /Users/j3di/Desktop/Dev/Tic/tetris.lua
```


It's work, it launch tic et load the file.lua but dont load I think the cart I don't see sprites in sprite editor or in map :-/

I forgot something?

**Comment by nesbox** [comment] 2017-04-09 09:25
@Gi972 
Are you sure you've installed tic .21 to the Application folder, because `-code` argument was added in .21 ?

**Comment by Gi972** [comment] 2017-04-09 22:18
Ok I try in put the file tetris.tic and tetris.lua in the same folder and it works.

I understand I forgot in my precedent post the path in the  second argument of tetris.tic
The correct command is:

```
MacBook-Pro-de-Gi:Tic j3di$ /Applications/tic.app/Contents/MacOS/tic /Users/j3di/Library/Application\ Support/TIC-80/0.21.0\ dev/tetris.tic -code /Users/j3di/Desktop/Dev/Tic/tetris.lua
```

Hope that help other users
thanks for your patience and help

**Comment by Gi972** [comment] 2017-04-09 22:19
So for the main subject do you think comment/uncomment it's a bad idea?

**Comment by nesbox** [comment] 2017-04-10 07:17
@Gi972 it's a great idea :)
I'll add `CTRL + /` (`CMD + /` on Mac) to comment/uncomment line

**Comment by nesbox** [comment] 2017-05-03 20:35
Added line comment/uncomment by `CTRL/CMD+/`

![comment](https://cloud.githubusercontent.com/assets/1101448/25680322/0fe31152-3059-11e7-991c-4e374a96c5bb.gif)

done on .23

**Closed by nesbox** 2017-05-03 20:35 UTC
Labels: feature
