### ISSUE TITLE
Black borders

### ISSUE THREAD

**Issue by JeremyJohn2** [nesbox/tic.computer#12] opened 2017-01-23 14:56 UTC
As you requested i'm creating an issue here about the black borders that are present in some resolutions.

**Comment by nesbox** [comment] 2017-01-23 15:09
info for me: add 'pixel-perfect' variable to config and to command line parameters

**Comment by nesbox** [comment] 2017-02-20 13:49
Not sure if the issue is actual because you can control color of the "black border" area
https://twitter.com/tic_computer/status/826846225324527619
<blockquote><p lang="en" dir="ltr">You can define border color by 0x3FF8 address in the RAM, can be useful with creating &quot;ambient lighting&quot; effects :) <a href="https://t.co/uJOddm6rBy">pic.twitter.com/uJOddm6rBy</a></p>&mdash; TIC-80 (@tic_computer) <a href="https://twitter.com/tic_computer/status/826846225324527619">February 1, 2017</a></blockquote>

**Comment by nesbox** [comment] 2017-05-09 10:52
rendering is always pixel perfect without stretching and you can change color of black border
closing...

**Closed by nesbox** 2017-05-09 10:52 UTC
Labels: discussion
