### ISSUE TITLE
Better default keyboard controls for the second player.

### ISSUE THREAD

**Issue by darkhog** [nesbox/tic.computer#196] opened 2017-06-17 18:17 UTC
Current second player controls makes it really hard to play two player games on a keyboard with no external controllers. Fortunately that can be resolved by using following controls for the second player:

up/down/left/right: Num8/Num2/Num4/Num6
a/b/x/y: Num5/Num7/Num9/Num0

This way the second player will be able to play using just one hand. "A" key will be under Num5 which means easy shooting/jumping, while b/x/y will be also easy to reach (y with a thumb and b/x with index/ring fingers).

What do you think?

**Comment by Viza74** [comment] 2017-06-21 11:26
I guess a sizeable percentage of laptop users don't have a numpad (myself included), so that's could be the reasoning behind the default layout.
Just guessing here.

**Comment by harraps** [comment] 2017-06-30 12:12
It would be great if we could define custom keyboard inputs in the metadata of the cartridge using a hexadecimal sequence to link the buttons with the keys
I've made a game on itchio which could be played with up to 6 players but the key input for most players are awkward.

**Comment by darkhog** [comment] 2017-07-11 13:16
Viza, laptop keyboards aren't good to play 2player games on them without external controllers anyway so that should be of no concern.

**Comment by Viza74** [comment] 2017-07-11 16:59
Uhhhmmm, a couple of thoughts spring into my mind relating to this issue:

- There is now a way to reconfigure the key mapping in TIC, so this issue is maybe already... outdated?... 
Although I think the keyboard remapping not necessarily the most end-user (= player) friendly right now, because they have to drop out of the game and type in a command, which not necessarily obvious for someone who just want to play. Assuming the end-users are (or will be somewhere along the line) the players and not geeks like us, who want to hack on games. :)

- For me there is no default key mapping for the second player if I launch TIC, which also sort of make this issue a non-issue. Assuming that it is not a bug, but the designed behaviour :)
Reconfiguring the keymap will be saved for future "empty" launches. I'm not sure (I did not check) if it is a "global option", saved to the player's machine, or if it is gets saved in the cart too.

- You opened this issue to avoid forcing the players to use of external controllers because of the not-necessarily-ideal default layout, and now you suggest that everybody on a laptop/missing numeric keyboard should be forced to use an external controller anyway? I'm not sure I can follow your logic :)
I'm also not sure that normal keyboards with a numpad are very good for multiplayer games because of keyboard ghosting. But actually I have no experience on if the numpad keys are usually anti-ghosted or not? 

Anyway, as I mentioned before I just guessing here, as always.  There were a couple of occasions when I was wrong with my guesses, so I wouldn't be surprised if I was wrong again here. :)

**Comment by darkhog** [comment] 2017-07-26 22:15
Desktop keyboards usually come with a numpad. As for ghosting, these keybinds were sorta lifted from Liero, a very cool DOS game that inspired games such as Teeworlds and OpenLieroX and I know for a fact that you can play Liero with a buddy using these controls.

**Comment by Viza74** [comment] 2017-07-31 17:17
*Usually* came with a numpad.
I have 3 desktop keyboards at home, two of them have numpads. Also three laptops, only one of them have numpad. So across my domestic keyboard popullation :) the proportion is 50-50 :)
YMMV

I don't want to come off as some kind of anti-numpad zealot or something, I'm just saying that all my keyboards have ijkl keys.

And as I said I don't know if the numpad key are anti-ghosted or not, so thank you for the information.

**Comment by nesbox** [comment] 2017-09-15 12:12
default controls is empty for the second player
go to the game menu and map keys you want
closing...

**Closed by nesbox** 2017-09-15 12:12 UTC
Labels: wontfix
